### ISSUE TITLE
Unit Test Harness failing Test Cases that should pass

### ISSUE THREAD

**Issue by NewForester** [exercism/gnu-apl#17]
Issue seen with GNU/APL 1.6 and GNU/APL 1.7.

I don't wish to point fingers.  There is some confusion somewhere.  More than happy for it to be my poor understand of advanced features. 

For the 'hamming' exercise that are two test cases that expect the function under test to 'return' _LENGTH ERROR_ when one operand is scalar-like and the other operand is not.

The function:
```apl
∇z←A distance B
    ⎕ES ((≢A) ≠ (≢B)) / 5 3
    z ← +/ A ≠ B
∇
```
gives the expected result when invoked directly from the interpreter but not when invoked from the test harness.  This function:
```apl
∇z←A distance B
    'HELLO ERROR' ⎕ES ((≢A) ≠ (≢B)) / 5 3
    z ← +/ A ≠ B
∇
```
works with the test harness - it sees the function as 'returning' _LENGTH ERROR_ even though, when invoked directly from the APL interpreter, it is  seen as 'returning' _HELLO ERROR_.

**Comment by marnen** [comment]
`⎕ES` behaves strangely in GNU APL: although it throws the expected error to the interpreter, `⎕EC` doesn't see it that way. I believe this to be a bug, and I need to get around to reporting it to the GNU APL mailing list, but in the meantime, I don't know how else than `⎕EC` to test for error conditions. In my sample solution, I didn't use `⎕ES` for this reason, much as I would have wanted to. 

Do you have a suggestion as to how the test code could be written differently?

**Comment by AtelesPaniscus** [comment]
I will have a look at the test code and see if I can come up with a suggestion.  IMHO launch would be a bad idea without a work around for this.

APL, at the best of times, is difficult to read.  The 'hamming' exercise is straightforward enough for the 'good cases'.  I do not, and I doubt others would, consider it 'productive', to seek evermore obscure alternatives for the good cases in the hope of finding one that also throws the 'correct' error for the bad cases.

Take the next exercise, the 'RNA transcription':
```apl
∇z←to_rna DNA
    'DNA ERROR' ⎕ES (5 ∊ "GCTA" ⍳ DNA) / 5 4
    z ← (⊂ "GCTA" ⍳ DNA) ⌷ "CGAU"
∇
```
the second line handles the good cases and throws an error for all the bad cases.  It throws _INDEX ERROR_ instead of _DOMAIN_ERROR_ so it fails the bad cases.

I have fiddled with APL a lot this year but if I'd hit this a year ago I would have decided this was beyond me and given up.  I suspect a lot of other people would do the same.

**Comment by AtelesPaniscus** [comment]
```apl
⍝ expect DOMAIN ERROR
⎕ES 5 4

⍝ expect 0  5 4  DOMAIN ERROR ?
⎕EC '⎕ES 5 4'

⍝ expect OOPS
"OOPS" ⎕ES 5 4

⍝ expect 0  5 4  OOPS ?
⎕EC '"OOPS" ⎕ES 5 4'
```

**Comment by marnen** [comment]
> ⎕EC and ⎕ES do not behave well in concert.

Totally agreed. IMHO this is a bug, so I will probably report it as such, but I want to look again at the APL standard. 

> I have no access to documentation

You have just as much access as I do.  All the APL docs I'm using are freely available. 

> There is no work around you could implement in your code.

There is, and I did. Look at the sample solution. :)

> For Exercism purposes, it will be sufficient for sluggers to use the dyadic form of ⎕ES with an empty string on the left hand side.

I think I disagree. If we are going to bother expecting solutions to throw errors (which perhaps we shouldn't at this stage after all), then they should throw the *right* errors. 

> I fear it will be necessary to make this very clear to sluggers

Probably.

**Comment by AtelesPaniscus** [comment]
> I want to look again at the APL standard.

> You have just as much access as I do. All the APL docs I'm using are freely available.

You have access to the standard ?  Wow.  I searched several times and concluded ISO and IBM were exercising copyright holder privilege.

I use the MicroAPL site which is fine, with a pinch of salt, for everyday purposes but I would not trust it to accurately describe how GNU APL should behave.  I would like to agree but the most assertive I can be "is this appears to me to be a incorrect behaviour".

>> There is no work around you could implement in your code.

I am sorry my English is ambiguous.  What I meant was "There is no work around that can be implemented in _test.apl_ (aka your code):  the issue will have to be addressed in GNU APL (aka their code). I hope this is clear.

**Comment by AtelesPaniscus** [comment]
>> For Exercism purposes, it will be sufficient for sluggers to use the dyadic form of ⎕ES with an empty string on the left hand side.

I wish to withdraw that statement.  GNU APL appears are worse than I thought.

> I think I disagree. If we are going to bother expecting solutions to throw errors (which perhaps we shouldn't at this stage after all), then they should throw the right errors.

I agree with the sentiment.  If you are going to do things, then do them right.

My earlier rant was as a slugger (LoL, student - what term do you prefer ?).  I am following several Exercism tracks.  GNU APL was the first where I felt it was harder to solve exercises than it was to just use the language.  I understand some of the difficulties you are facing but the average slugger won't and, if they belong to a "I want it all and I want it now" generation, they won't care either.

I've thought long about this and tried a few things and, well, oh dear.

Here is my first attempt at the RNA Transcription exercise in APL:

```apl
#!/usr/bin/env apl --script

∇z←to_rna DNA
    'DNA ERROR' ⎕ES (5 ∊ "GCTA" ⍳ DNA) / 5 4
    z ← (⊂ "GCTA" ⍳ DNA) ⌷ "CGAU"
∇
```

In another language, I might use:

```python
    raise ValueError
```

or I might use:

```python
    1 / 0
```

The first is unambiguous and uses the language well, the second exploits a side effect of division by zero and, I expect, would attract criticism.  The Exercism exercise does not care as long as the 'right' exception is thrown.  However, if Exercism is, as I hope, about learning to code well, I would not want to see any track to encourage the division by zero approach.  My concern is how the GNU APL track can do this.

Using ⎕ES, I guess, is using the language well but GNU APL seems to know otherwise ... if programmers used ⎕ES then the bugs would have been reported and fixed long ago.

I tried:

```apl
#!/usr/bin/env apl --script

∇z←raise_domain_error condition
    '' ⎕ES condition / 5 4
∇

∇z←to_rna DNA
    raise_domain_error (5 ∊ "GCTA" ⍳ DNA)
    z ← (⊂ "GCTA" ⍳ DNA) ⌷ "CGAU"
∇
```

Other tracks provide an 'empty' solution as a starting point and sometimes 'empty' is not quite empty.
I thought that if the APL exercise provides _raise_domain_error_ with a comment to the effect "You don't have to use this but it may help if you do", then (most) of my concerns would be addressed.

However, this does not work.  You get VALUE ERROR because ⎕ES returns no value (if it does not throw an exception).  I suspect this conforms to the standard but it would appear that GNU APL only copes with no value being return at the top level of the interpreter.  It does not cope with subroutines returning no value as far as I can tell.

I tried every alternative I could think off but all upset GNU APL.  When I say upset ... the nice log the test harness normally prints wasn't.

So I ended up with:

```apl
#!/usr/bin/env apl --script

∇z←domain∆error condition
    z ← condition ÷ 0
∇

∇z←to_rna DNA
    z ← (⊂ "GCTA" ⍳ DNA) ⌷ "CGAU" ⊣ domain∆error 5 ∊ "GCTA" ⍳ DNA
∇
```
I do not like this much but at least the side effect is named and shamed.
