### ISSUE TITLE
Request for admin permissions

### ISSUE THREAD

**Issue by marnen** [exercism/gnu-apl#40]
I'm the primary maintainer for this repo, but it looks like I don't have administrative permissions on it. Can we fix that?

**Comment by ErikSchierboom** [comment]
I see that you are in the [`maintainers.json` file](https://github.com/exercism/gnu-apl/blob/master/config/maintainers.json), so that's great. This is possibly due to the permissions not having been updated correctly.

@iHiD Could you run your permissions script?

**Comment by iHiD** [comment]
Hi @marnen. You have write permissions already. We don't give out admin permissions on repos. Is there something you need doing?

**Comment by marnen** [comment]
@iHiD The proximate issue that led me to notice this was that I have no way to merge with a merge commit from the GitHub UI—only squash is enabled (which I detest), and I don't have the admin permissions to change that setting.

But the larger issue is that as the primary maintainer of this track repo, I think it just makes sense to give me admin permissions. Otherwise I don't really have control of the track in the way that I'd like to have.

**Comment by iHiD** [comment]
I've turned merge commits on for you.

> I guess I'm not sure why you wouldn't give me admin permissions on a repo that I originated and have been almost the only committer on.

No-one has admin permissions on any Exercism repos, other than Katrina or I. There are two reasons:
1. No-one needs them.
2. They come with danger to the organisation.

Dangers include:
- Giving admin permissions allows people to create arbitary GitHub actions that can do all sorts of things under exercism's banner.
- Admins can delete tracks.
- Admins can circumvent the CODEONWERS protections to add other maintainers, which then allow updates in `problem-specification` to be auto-merged by a malicious party.

If someone else gained control of your account for any reason then they could do any of these things, which would all be bad. I personally face people trying to access my exercism Google apps account to try and gain access on a regular basis. Exercism is a high-ranking website, and has enough reputation that it's great for spammers and their ilk. We're therefore a target for attack.

Based on the fact that there is no advantage to anyone having admin permissions, and there is lots of risk associated, we just don't give them to anyone - only the two account owners have them.

**Comment by marnen** [comment]
@iHiD:

> I've turned merge commits on for you.

Thanks very much.

> No-one has admin permissions on any Exercism repos, other than Katrina or I.

To me as a track maintainer, that's a worrisome organizational decision. It makes me feel less like I'm contributing to a shared project, and more like I'm essentially here on someone else's sufferance. It makes me less likely to do upkeep on my track (not that I've been great about that in the past, admittedly, but the fact that Exercism doesn't trust me to admin my own track repo means that I'm now reevaluating whether I even want to continue my association with the Exercism project!).

> No-one needs them.

How do you figure that? I had to get you involved to change a setting which should have been a 5-second option change for me, and which does not have any negative implications for the larger project as a whole AFAIK.

> Giving admin permissions allows people to create arbitary GitHub actions that can do all sorts of things under exercism's banner.

Are you worried that a malicious track admin would create a CI action that does something that it shouldn't?

> Admins can delete tracks.

Track maintainers *should* be able to delete their tracks, IMHO.

> Admins can circumvent the CODEONWERS protections to add other maintainers

Are you saying that *every* maintainer on *every* track has to be personally approved by Exercism? (I didn't realize that because I've never tried to add another maintainer on this track.) That seems like a lot of extra admin work for you folks.

It also seems like security theater. When I created this track, the approval process was pretty perfunctory as far as I could tell—but then again, it did involve an actual conversation with Katrina, so I guess she could verify that I was a real developer, not a bot or someone malicious.

> If someone else gained control of your account for any reason then they could do any of these things, which would all be bad.

So you're saying that you don't trust maintainers to keep their GitHub accounts secure, and that this is a sufficient reason for keeping them from admin permissions on their tracks?

Hmm. Maybe I should move development on this repo to a fork outside the Exercism org and ask Exercism to fork it. That would allow me to have admin rights without worrying about tainting the Exercism org...

**Comment by iHiD** [comment]
> Track maintainers should be able to delete their tracks, IMHO.

I think this sums up everything pretty well. If a JavaScript maintainer decided to delete the JavaScript track tomorrow, 92,000 students would suddenly find themselves all their work broken and usable. That's not an acceptable risk for Exercism to take. The fact that you're not malicious, but that you feel that that might be a reasonable decision to make, and the fact that you could have a disagreement and decided that you want to ragequit and take the track with you, isn't a realistic option for us to have.

> So you're saying that you don't trust maintainers to keep their GitHub accounts secure, and that this is a sufficient reason for keeping them from admin permissions on their tracks?

I don't trust myself to keep things secure! :) The fact that I could accidentally delete Exercism literally keeps me awake at night. Therefore the fewer other people that have to worry about this, the better. 

---

Said with respect, I think there's a risk that you could be taking this decision as a personal affront, rather than a security precaution. There's no route to getting admin permissions that you're not being included in. Exercism's staff (e.g. @ErikSchierboom) don't have admin permissions (and don't want them). You're the first maintainer ever to request admin permissions - I know for sure that many others are grateful they don't have that worry, and in fact the recent change to enforce CODEOWNERS on the `maintainers.json` came from the maintainers wanted to ensure that risks were minimised. Exercism is an organisation, which exists to do something really well, and as part of that, we take careful precautions. To take a different example, if I contributed to, or even became a maintainer of Firefox, I wouldn't expect I'd get the right to delete the bit of the codebase I was working on and break the browser as a result - the same applies for Exercism.

**Comment by marnen** [comment]
@iHiD:

>  If a JavaScript maintainer decided to delete the JavaScript track tomorrow, 92,000 students would suddenly find themselves all their work broken and usable.

Wait what? Deleting a track repo would break students' existing work on that track? I confess I'm surprised.

> Said with respect, I think there's a risk that you could be taking this decision as a personal affront, rather than a security precaution.

I'm not taking this personally at all. I just think it's an odd way to set up a distributed project like Exercism.

**Comment by iHiD** [comment]
> which is why not having admin rights on this repo seemed so off.

Understood. The reason for not having a monorepo is really just noise-signal. The [v3 repo](https://github.com/exercism/v3) for example currently has 127 open PRs and 387 issues. The [main exercism repo](https://github.com/exercism/exercism) has another 464 issues open. Today, Erik managed to ask for review from about 140 people by accidentally requesting the wrong team. These are the problems that having large monorepos gives us and why we have separate track repos.

My mental model of the Exercism Org is that its one single space that powers the website. The demarkation of repos within it is always purely practical. The data from it is live streamed onto the website (the website uses git internally for all the exercise it shows). Amongst these repos we many repos that write to s3, some that write to DockerHub, others that write to ECR. The repos themselves, through GitHub actions, effectively act as a large piece of software working together to power things.

> I just think it's an odd way to set up a distributed project like Exercism.

Yep - fair enough. But while it's a distributed project in terms of writing software, it's also a live website that thousands of people use daily, and so the consequences of breaking it are substantial.

FWIW, I spent 2yrs working on exercism and put a lot of money (>$150k) into it, to get v2 built and didn't have admin permissions for any of that period. It was only after v2 launched, when Katrina invited me to become co-founder, that we decided it was pragmatic for me to have GH admin permissions, and that was mainly so I could do things rather than her having to gatekeep everything. Still today, there are lots of bits that Katrina doesn't have admin access to, because she doesn't need, and that's her preferred position to have. 

I guess to summarise simply, we have an org-wide approach that everyone has the absolute minimum access they need. Everything is OSS and so people can fork and do what they want with the code. But the "live" thing that is the Exercism GitHub organisation, website, and other related things, we take that precaution.
